### ISSUE TITLE
astro  를 github actions 배포 시 GISCUS 환경 설정

### ISSUE THREAD

**Issue by tkhwang** [tkhwang/tkhwang.github.io#1]
`.github/workflows/deploy.yml` 에서 다음과 같이 사용 : `vars.XXX` 는 repository variable 을 이용함.

```
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      SITE: ${{ vars.SITE }}
      GISCUS_REPO: ${{ vars.GISCUS_REPO }}
      GISCUS_REPO_ID: ${{ vars.GISCUS_REPO_ID }}
      GISCUS_CATEGORY: ${{ vars.GISCUS_CATEGORY }}
      GISCUS_CATEGORY_ID: ${{ vars.GISCUS_CATEGORY_ID }}
```

## Configuration

Secret 과 variable 구분 주의해야함.

repository settings > Secrets and variables > actions > Variables > `Repository variables`
